### ISSUE TITLE
Feature Request: Customer Account

### ISSUE THREAD

**Issue by willholsten** [dlerm/shopify-wishlist#26]
It would be nice to link a wish list to the customer account so they can be saved and viewed on multiple devices. Maybe using customer metafields which are coming soon?

If a customer is not signed in but adds products to wish list then it will ask for an email to assign it to. (Problem is anyone could add products to an emails wish list and we may need a server to create wish list for emails without an account)

Or if a customer is not signed in and adds to wish list then it will save to local storage and if customer then creates account or signs in it pushes local storage wish list to their account.

**Comment by jobincleetus** [comment]
@dlerm it would be great if this is somehow possible, your thoughts?

**Comment by dlerm** [comment]
@willholsten @jobincleetus I recently uploaded a new repo that is the backend component for saving wishlists to customer metafields ([repo](https://github.com/dlerm/shopify-wishlist-app)). I'm working on setting up some sample files that act as an interface between the app and with this repos's theme files -- but haven't finished it yet. 

If you are familiar with NodeJS please take a peek at the backend solution and feel free to implement it however you see fit.
