### ISSUE TITLE
Products are added correctly but not showing on my wishlist page

### ISSUE THREAD

**Issue by leorprt** [dlerm/shopify-wishlist#28]
Hi @dlerm thank you for your amazing work and for the time you put in. 

I'm just facing an error right now: when I add products to the wishlist by clicking the heart button, it works.
However they are not displaying on my wishlist page. 

No error displaying on console and if it could helps, I use Prestige theme (2.0 online store version). 

Do you have an idea from where the error could come please?

Thanks !

**Comment by dlerm** [comment]
@leorprt My first thought is that the product card selector in `Wishlist.js` is not accurate to your theme's product card.
```javascript
// line 6 - 10
const selectors = {
  ...
  productCard: '.product-card', // This should match the outer most classname from your product card snippet
};
```

That selector is crucial in properly extracting the product card HTML inside the `fetchProductCardHTML` function. If the logic doesn't find that selector, nothing will get loaded /appended on the wishlist page.

**Comment by leorprt** [comment]
Ok it works I have my product now thank you but there's one error that persists: only the image is showing.
How can I show also the title and the price of the product ?

**Comment by dlerm** [comment]
@leorprt I think the product card snippet for your theme accepts a few snippet variables that control which content it displays. If so, you will want to include those variables inside the snippet call on the `product-card-template` section.

I will probably look something like this:
```
{%- render 'product-item', product: product, show_product_info: true, show_vendor: true, show_color_swatch: true, show_letter_swatch: true, show_labels: true -%}
```
Note: swap `true` >> `false` for any variables/display you want to disable.

**Comment by leorprt** [comment]
Thanks ! You're the boss ;)
