### ISSUE TITLE
how to count the products i have added in wishlist

### ISSUE THREAD

**Issue by TonyChoy** [dlerm/shopify-wishlist#3]
hi @dlerm 
can this `{{     page.products.count   }}` code work on "page.wishlist.liquid", and show the total in page ?

one more you can see if cart have product it will have a dot.
![wishlist-console-screenshot](https://user-images.githubusercontent.com/21098180/50887950-70343980-142f-11e9-94cc-fdc3c01daadd.png)

```
<a href="/cart" class="site-header__link site-header__cart" alt="Cart" title="Cart" >
{% include 'icon-cart' %}
<span class="icon__fallback-text">
{{ 'layout.cart.title' | t }}
</span>
<span class="site-header__cart-indicator {% if cart.item_count == 0 %}hide{% endif %}">
</span>
 </a>

```
below is my wishlist icon . **how can i have a dot like cart**?

can i use this
```
 <span class="site-header__cart-indicator {% if page.wishlist.item_count == 0 %}hide{% endif %}">
</span>`
code to make it?
```
          

```
<a href="/pages/wishlist" class="site-header__link site-header__cart" alt="Wishlist" title="Wishlist" >
 {% include 'icon-wishlist' %}
<span class="icon__fallback-text">{{ 'layout.wishlist.title' | t }}
</span>
<span class="site-header__cart-indicator {% if page.wishlist.item_count == 0 %}hide{% endif %}"></span>
</a>
```

**Comment by dlerm** [comment]
@TonyChoy Unfortunately this wishlist module will not allow you to print the wishlist item count inside of the liquid template. However, you can display the wishlist item count from within the Javascript. 

I've added a function in [Wishlist.js](https://github.com/dlerm/shopify-wishlist/blob/master/assets/Wishlist.js) called **updateWishlistItemCount** to do this. Please copy my example. 

For this to work you need to make sure to:
1) Set the variable **$wishlistItemCount** to point to an element on your page where you want the wishlist item count to show up
2) Call the **updateWishlistItemCount** function inside the **Wishlist.init** function at the bottom of the file

Give this a try and let me know if it works for you.
