### ISSUE TITLE
product fetch url is returning data for some example product and not the actual product

### ISSUE THREAD

**Issue by msachdev0307** [dlerm/shopify-wishlist#31]
when the data is to be displayed in the wishlist page '/product/handle?view=card; fetch url is returning data for some example product and not the actual product 

![image](https://user-images.githubusercontent.com/102185955/159566350-1bcfe71c-0cb1-4351-914b-781de8cd89fa.png)

**Comment by dlerm** [comment]
@msachdev0307 Can you post the content of the product-card section? May be some hard coded values in there.

**Comment by dlerm** [comment]
@msachdev0307 I think the issues is that we are passing the product data into the snippet incrrectly.

Your snippet requires the product variable to be named `card_product` (instead of just `product`).

In the section `product-card-template`, change the snippet to be called like this:
```
{% render 'card-product', card_product: product %}
```
