### ISSUE TITLE
Wishlist in Dawn Theme 5.0.0

### ISSUE THREAD

**Issue by shopify-dawn** [dlerm/shopify-wishlist#34]
Hi, I followed all the steps, but it didn't work.
I can't even see the heart icon.
What should I add or remove to the code so it work

Note: I'm using the latest Dawn version 5.0.0

Thank you.

**Comment by dlerm** [comment]
@shopify-dawn can you try adding explicit `width` and `height` attributes to the `svg` element inside the file **icon-heart.liquid**?

**Comment by shopify-dawn** [comment]
On top of each product, appear a big heart. Some are not clickable and others take you to the product page
![image](https://user-images.githubusercontent.com/105659963/169651314-62d054b9-cbfd-4ed3-9989-942902faaebf.png)

**Comment by shopify-dawn** [comment]
Note: When I change the numbers, the stroke-width does change, but the heart size stays the same.

**Comment by dlerm** [comment]
@shopify-dawn Do you have any site specific styling applying to buttons or SVGs that would cause the SVG to be positioned outside the button? The button is the only part that has functionality attached. The SVG is just a visual element.

**Comment by shopify-dawn** [comment]
No I don't. I used the wishlist in a new unstyled dawn theme to see if it works.
