### ISSUE TITLE
wishlist page product title and product price can't show

### ISSUE THREAD

**Issue by vasu-kanani** [dlerm/shopify-wishlist#35]
In prestige theme add wishlist code and do some changes but in wishlist page product title and product price can't show please check

**Comment by TarmiBen** [comment]
if it's still useful, in the product-card-template view comes the render of the product template and sends the product there
`{%- render 'product-card', product: product -%}`

However, it sends "**product**" but in your product-card it may be defined differently, in my case it receives it with the name "**product_card_product**" and it would be as follows
`{%- render 'product-card', product_card_product: product -%}`
