### ISSUE TITLE
No Items are showing on the wishlist page

### ISSUE THREAD

**Issue by kingsley91au** [dlerm/shopify-wishlist#36]
Hi there,

There are no items showing on the wishlist page, could you please help?

Kingsley

**Comment by Andyrei** [comment]
What error are you getting on the console?

**Comment by dlerm** [comment]
@kingsley91au Hey The classname selector for your product card snippet may differ from theme to theme. If you view the product card snippet file you are using, you should find the classname on the outer most element in the snippet. Once you have that classname, update the `Wishlist.js` file in the `selectors` variable to reference the new classname.

Example:
Product card classname: `product-item` (this will likely be different for you)
```
const selectors = {
  button: '[button-wishlist]',
  grid: '[grid-wishlist]',
  productCard: '.product-item', // updated to match my product card classname
};
```
