### ISSUE TITLE
Products not displayed in wishlist page but added to localStorage

### ISSUE THREAD

**Issue by Harikaa123** [dlerm/shopify-wishlist#4]
Only the first 50 products from(collections/all) are being to wishlist. From 51 to rest products are not displayed in wishlist page even though they are being added in localStorage. Please help me out..
![screenshot 711](https://user-images.githubusercontent.com/47736462/52936020-ff166900-3380-11e9-9304-1066545d4ea0.png)

**Comment by dlerm** [comment]
@Harikaa123 D0 you have line 8 and 12 that override the default pagination? [See here](https://github.com/dlerm/shopify-wishlist/blob/master/templates/page.wishlist.liquid). That should allow it to get past the default 50 product limit.
```
{% paginate collections.all.products by 9999 %}
...
{% endpaginate %}
```

**Comment by anilviradiya** [comment]
If 200+ Products then it's not working.
Thanks
