### ISSUE TITLE
On wishlist page product title and image not showing

### ISSUE THREAD

**Issue by yogesh1run** [dlerm/shopify-wishlist#46]
On wishlist page there is product title and image not showing instead of these there is Example title showing

Please check here
https://prnt.sc/rc6wG6a88rJn

**Comment by dlerm** [comment]
@yogesh1run That sample screenshot looks partially correct. The product title is showing up but the image is not.

Just FYI - the "product.card.json" template view is meant to be style-less - it's just raw html.

On that special template view, can you open your browser dev-tools element inspector and post a screenshot of the product card element with all sub elements expanded?

**Comment by dlerm** [comment]
I think the issue is actually that we are passing the product data into the product card snippet with the wrong variable name.

I think you want to use it like this (inside of `sections/product-card-template.liquid`):
```
 {%- render 'card-product', card_product: product -%}
```
