### ISSUE TITLE
How can i show Wishlist item in popup instead  of page 

### ISSUE THREAD

**Issue by motiuleasital** [dlerm/shopify-wishlist#48]
I'm looking for a solution to display wishlist items in a popup when clicking the wishlist button in the header counter, rather than redirecting to the wishlist page. Can anyone assist in resolving this matter?

**Comment by dlerm** [comment]
@motiuleasital to make the wishlist items populate inside a pop, you could copy the HTML code from the `wishlist-template` section and paste it into your popup code. 

Then whenever your popup opens, you need to call the `initGrid()` function from the Wishlist.js file which will load and file the wishlist grid HTML with the actual products.

I haven't tested this, but it should work.
