### ISSUE TITLE
i have followed exactly these steps but couldnt get wishlist

### ISSUE THREAD

**Issue by aaryyanvivek** [dlerm/shopify-wishlist#6]

**Comment by aaryyanvivek** [comment]
I am using a theme which already has a wishlist, but its not working (whenever i click on wishlist button its asks me to log in, when i log in, it says error 404) thats why im manually trying to add wishlist, but i cantt

**Comment by dlerm** [comment]
@aaryyanvivek This solution is not compatible with any other wishlists. It's more of a shopify/js hack to create the appearance of a wishlist.
