### ISSUE TITLE
How to add product to wishlist using ajax

### ISSUE THREAD

**Issue by gautam14** [dlerm/shopify-wishlist#7]
Hello @dlerm 
How can we add the product to wishlist using ajax, when we click on wishlist icon. 

Thank you!

**Comment by dlerm** [comment]
@gautam14 By default no ajax is needed as the wishlist is built/edited via [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) which is synchronous. There is no API or HTTP request happening. What use-case are you try

**Comment by gautam14** [comment]
I just want to show an alert message with product details when added to wishlist and update the counter in the header without refreshing the page.

**Comment by gautam14** [comment]
@dlerm Please guide me on how can I implement this if it is possible. Thanks!

**Comment by dlerm** [comment]
@gautam14 
1) You can insert your alert in Wishlist.js function `updateWishlist` just under the `localStorage.setItem(...)` (lines 31 & 36). There are many ways to show the product data within the alert. One way is to make an ajax request to `/products/<handle-from-withlist-btn>.json`, and use that response to populate the alert with product data.
2) You can have the wishlist counter update in the header by updating a line in Wishlist.js to point to a css selector for your header `var $wishlistItemCount = $('.wishlist-item-count');` (line 5)

**Comment by gautam14** [comment]
@dlerm Thank you!
