### ISSUE TITLE
Adding Wishlist to existing theme

### ISSUE THREAD

**Issue by msango1** [dlerm/shopify-wishlist#8]
Hi Dlerm!

Thanks for the code! But I'm new to coding and having a nightmare adding the elements to my existing store.

I have added the <div classes> to my product.liquid file but not able to see any element. From here by brain is fried...

Thanks,

M

**Comment by emmandichoso** [comment]
@msango1 I think that depends on your theme structure. If you have something like on the product.liquid: 

{% section 'product-template' %}
{% section 'related-products' %}
{% section 'recently-viewed-products' %}

then you should check "product-template"

If you have a conditional like this on product-template:
          {%- if product.template_suffix != 'coming-soon' -%}
            {%- include 'product-form' -%}
          {%- endif -%}

Then you should check product-form.liquid

**Comment by mohinpatwary** [comment]
Hi Dlerm!
Website link: http://shop.ellelooks.com
I am getting a message from the customer. They constantly message me that wish lists are not being saved on the wish list page. I used properly code in my theme. But I don't understand where the problem? 

I can show my code? Could you please Help me

Thank you

**Comment by rjtbansal** [comment]
Hi,

I am using impulse theme. Unable to see any icons on my pages. Im placing the snippet in product.liquid. Any insights as to what could be going wrong?

**Comment by rjtbansal** [comment]
So adding the snippet to product-grid-item.liquid renders the icon nicely. However page.wishlist doesnt still show up in dropdown. Any guidance on this would be very helpful. Thanks!

**Comment by dlerm** [comment]
@rjtbansal Did you add the template to the live theme or an unpublished theme? The template needs to be on the live theme for it to populate within the template dropdown in the pages admin.

**Comment by dlerm** [comment]
@mohinpatwary Implementing this requires at least some development knowledge. Is there any console errors coming from the wishlist scripts? Are you customers browsing incognito mode or clearing their browser data? Incognito mode will clear localStorage after the browser is closed. If you can identify the problem a bit better I may be able to help more.

**Comment by rjtbansal** [comment]
> @rjtbansal Did you add the template to the live theme or an unpublished theme? The template needs to be on the live theme for it to populate within the template dropdown in the pages admin.

That explains it. I am on unpublished theme currently. Is there an alternative as I am hesitant to publish it just yet as it could impact the client. :(

**Comment by dlerm** [comment]
> > @rjtbansal Did you add the template to the live theme or an unpublished theme? The template needs to be on the live theme for it to populate within the template dropdown in the pages admin.
> > Thanks for your reply. And very helpful solution!
> 
> That explains it. I am on unpublished theme currently. Will give it a try by making it live.

@rjtbansal There's 2 way to handle that:
1. Add the template to the live site but have the template there be blank (no liquid or anything). It will still populate the dropdown ass needed. -- OR --
2. In your unpublished theme, when viewing the wishlist page that you want to see the page.wishlist template applied to you can use the `view` url param to apply the template on the fly:
```
https://yourstore.com/pages/wishlist?view=wishlist
```

**Comment by rjtbansal** [comment]
@dlerm  Thanks for these workarounds! I ended up following the first step and it really helped! Thanks a lot for this very helpful functionality instead of involving apps.

**Comment by dlerm** [comment]
> @dlerm Thanks for these workarounds! I ended up following the first step and it really helped! Thanks a lot for this very helpful functionality instead of involving apps.

@rjtbansal No problem! I highly recommend using the v2 that I published on Github recently - it uses AJAX loading on the wishlist page instead of loading all products which is way more performant and less error prone.

**Comment by rjtbansal** [comment]
> > @dlerm Thanks for these workarounds! I ended up following the first step and it really helped! Thanks a lot for this very helpful functionality instead of involving apps.
> 
> @rjtbansal No problem! I highly recommend using the v2 that I published on Github recently - it uses AJAX loading on the wishlist page instead of loading all products which is way more performant and less error prone.

Awesome! Will give that a try.

**Comment by rjtbansal** [comment]
@dlerm  Another issue I am facing is that my images dont show up in the wishlist. Product title, price including its image swatches show up. Im using Impulse theme where my products load in product-grid-item.liquid. Thats the file I am suing for render in product.card.liquid. 

Any ideas what could be going wrong with the image?

**Comment by dlerm** [comment]
> @dlerm Another issue I am facing is that my images dont show up in the wishlist. Product title, price including its image swatches show up. Im using Impulse theme where my products load in product-grid-item.liquid. Thats the file I am suing for render in product.card.liquid.
> 
> Any ideas what could be going wrong with the image?

@rjtbansal Is there image lazy loading that is not firing? If you inspect the image, do you see an active `src` attribute?

**Comment by rjtbansal** [comment]
> > @dlerm Another issue I am facing is that my images dont show up in the wishlist. Product title, price including its image swatches show up. Im using Impulse theme where my products load in product-grid-item.liquid. Thats the file I am suing for render in product.card.liquid.
> > Any ideas what could be going wrong with the image?
> 
> @rjtbansal Is there image lazy loading that is not firing? If you inspect the image, do you see an active `src` attribute?

It is actually complaining about srcset:
![image](https://user-images.githubusercontent.com/8683116/99720823-511b7f80-2a7c-11eb-9c0c-1a757d92e104.png)

And I see these errors in the JS console:
![image](https://user-images.githubusercontent.com/8683116/99720900-68f30380-2a7c-11eb-8231-55d292b2f7fe.png)

Whereas this isnt the case when I normally load products within collections.

**Comment by dlerm** [comment]
@rjtbansal Its actually an issue with the way I called the snippets using the newer `render` tag instead of the older `include` tag. Your code relies on the older tag so you just need to replace the instances of `(%- render '<snippet-name>' -%}` with `(%- include '<snippet-name>' -%}`

**Comment by rjtbansal** [comment]
Wow @dlerm I did exactly that prior to seeing your comment. Now the good thing is that it has solved part of the problem. I now can see an image upon hovering which wasnt the case earlier and I also dont see these console errors. But still, I dont see the main images getting loaded even now unfortunately.

**Comment by dlerm** [comment]
@rjtbansal Hmmm, would you be willing to share your unpublished theme's preview link? Seem like we need to inspect the non-hover image for any issues, or double check that the initial lazy load function is being called on this new template.

**Comment by rjtbansal** [comment]
Here: https://zuzsnz06ofx9un5e-7449541.shopifypreview.com

However for some reason, when I click on a collection, it falls back to published theme. Let me know if there is another way to share.

**Comment by dlerm** [comment]
> @dlerm Here: https://zuzsnz06ofx9un5e-7449541.shopifypreview.com
> 
> However for some reason, when I click on a collection, it falls back to published theme. Let me know if there is another way to share. I really appreciate all your help so far. Im more of a MERN stack dev, this ecosystem is very new for me.

@rjtbansal Thanks for sharing! I was able to inspect the product-grid-item's main image and noticed there was some class CSS on it that is setting the opacity to 0. See my screenshot here: https://prnt.sc/vml7cp. It seems there is some CSS animation to fade in the images based on the class `aos-animate` being present on the product grid container element.

Here's what you can do to make the grid show the items properly (with a nice fade effect you have built in)
In the `Wishlist.js` file, update your `setupGrid` function to look like this:
```
var setupGrid = function (grid) {
  var wishlist = getWishlist();
  var requests = wishlist.map(function (handle) {
    var productTileTemplateUrl = '/products/' + handle + '?view=card';
    return fetch(productTileTemplateUrl).then(function (res) {
      return res.text();
    });
  });
  Promise.all(requests).then(function (responses) {
    var wishlistProductCards = responses.join('');
    grid.innerHTML = wishlistProductCards;
    var buttons = grid.querySelectorAll(selectors.button) || [];
    if (buttons.length) setupButtons(buttons);
    grid.classList.add('aos-animate'); // This is the new part - it will add the animate class once the product have finished loading
  });
};
```

**Comment by rjtbansal** [comment]
@dlerm  Thank you so much! This works like a charm. I really appreciate all your efforts and quick replies :)

**Comment by rjtbansal** [comment]
Hi @dlerm ,  I have a loosely related question to wishlist. Are you aware of any social sharing apps that would work well with this wishlist? On our store we would like the ability to be able to share the wishlist. This I believe isnt straightforward at all since we are using localstorage to store data. I attempted to add an iframe from facebook but it would mostly work for sharing individual products. I tried [this app](https://apps.shopify.com/social-share-buttons-app?surface_detail=Social+share+buttos&surface_inter_position=1&surface_intra_position=5&surface_type=search) but all it does is try to generate a sharable wishlist URL which ofcourse wont work as our wishlist is dependent on user's own browser localstorage.

**Comment by dlerm** [comment]
> Hi @dlerm , I have a loosely related question to wishlist. Are you aware of any social sharing apps that would work well with this wishlist? On our store we would like the ability to be able to share the wishlist. This I believe isnt straightforward at all since we are using localstorage to store data. I attempted to add an iframe from facebook but it would mostly work for sharing individual products. I tried [this app](https://apps.shopify.com/social-share-buttons-app?surface_detail=Social+share+buttos&surface_inter_position=1&surface_intra_position=5&surface_type=search) but all it does is try to generate a sharable wishlist URL which ofcourse wont work as our wishlist is dependent on user's own browser localstorage.

@rjtbansal I have an idea that could likely solve for wishlist sharing. Would you mind opening up a new issue with this feature request? I'll connect a new pull request with that functionality to the issue once I've written the code.

**Comment by rjtbansal** [comment]
Thanks a lot @dlerm. Just opened this issue #12

**Comment by kannisabel** [comment]
@dlerm Hi, firstly, thank you for this! 
I manage to add the code successfully following your steps! However, I need some help to see if we can add the icon into the drawer in the header to link to the wishlist page?

![image](https://user-images.githubusercontent.com/80803536/111417325-9a28cb00-8720-11eb-8d6b-5eda6e5f4c38.png)

**Comment by virajpatil** [comment]
@dlerm Thank you for this!

please can you let me know the issue here 

https://shop.selfcareindia.com/pages/wishlist

getting message 

Liquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deep

**Comment by dlerm** [comment]
> @dlerm Hi, firstly, thank you for this! I manage to add the code successfully following your steps! However, I need some help to see if we can add the icon into the drawer in the header to link to the wishlist page?
> 
> ![image](https://user-images.githubusercontent.com/80803536/111417325-9a28cb00-8720-11eb-8d6b-5eda6e5f4c38.png)

@kannisabel Would you mind opening a separate issue so I can help you without digging through all these older comments?

**Comment by dlerm** [comment]
> @dlerm Thank you for this!
> 
> please can you let me know the issue here
> 
> https://shop.selfcareindia.com/pages/wishlist
> 
> getting message
> 
> Liquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deepLiquid error: Nesting too deep

@virajpatil Would you mind opening a separate issue so I can help you without digging through all these older comments?
